language: python
python:
- 3.6
- 3.5
- 3.4
- 3.3
- 2.7
cache: pip
install:
  - pip install -U tox-travis
  - gem install jekyll -v 2.4.0
  - gem install s3_website
before_script:
  - createdb judicious
  - pip install --upgrade pip
script:
  - tox
  - jekyll build
after_success:
  - cd docs; s3_website push; cd ..
deploy:
  - provider: heroku
    true:
      python: 3.6
    api_key:
      secure: VJuBGVe1G46Q8IWKWxX4MYcmsXzEP0hPOuU8DCGqtMWu1ZEHf8lHhhSS/r8PqpzGl6DJVit7oNH9OgWBWW5gx6jBfbk81FQeAolkmhmlSTPMOK/l2QjiM1C2klDcuStPcprF9uBfC7+TcPh0oEQal8GYwTHUdy+2NmzZ+5sTV5bKcpu9R6URBL5fzZvhOMB6H+Ws4Zo7L6dV9GI4I7crwXaMipjpIzfVQOVTAi1NSVKob9XWMaN//woWnH2ufNBZkGSvaycYCGDlx0wDTt68VnMs56Ub3Qr9aC7j9bFT9ufqOar6bmwSJTVzRqqvXqWFVLlCRCuYly9HHFyHjfAvX57IDndYPaqqY87/rEB4HKDuP7zeOT4AYd7ykAqxZga+0M3jsboos7fpgozvHb7uX3x1oz03mUBYgPTspjnOb+QTXTmLRPRPqqYfy21dyh6rVGl+rDelb6mCJhyY5x2JihAkQ9JhRjenHFVQxiiLJEbEwsoN1Bqn/z4LShNf8s5KX2EYM4d9IsTlUQCBZz2PS+Dsrv/bLcjsGYi1pi51SFtUT2XeCwDe799X+anqhPWLap/C3j3LchGmaK9+yUfHQeAHmVUAQwANlI29OD4rozhzUpBXPXQG1RFIw05sUmEZe2vfefpdBevuiAff2OxJO1gsLsHqofb63X9feP241YQ=
    app: imprudent
  - provider: pypi
    user: suchow
    true:
       python: 3.6
       repo: suchow/judicious
       tags: true
    distributions: sdist bdist_wheel
    password:
      secure: U53L/lZTXu+9Ag+yzLyHZVj14lxmsBXsT5cJFtJZqrtLgxkBS2iHpFlCJ1x1kowfgJySR+91tbSsJ4akJAzjLLG56F9vQqtEEYsNeFfwnZTwdGYSPKZ8WsnQprCUtMwOlFY1V+oPrTFOtTAim77y000ClscSWxEO4/Q7o10KYSfEhuLdnUkEO/7gzFIo0YC0ACAHpirRnaIWLFGuXxnUk2zyf1k/zmNWm74pQwvNWDothbtXCP8wP3zaR+Ah6z0XqpLvqX1djW+sJFovat9E8RuvTQSe+111n+DEC2ODoSpFfC68MR429cpzIlx02ZePX7Ul0U0/Sbo1XNY+/pvBCmJ9Pl0P9g1zL6J0/lD1yIrppimN+Fi1r3oShmOMDora0QH/yyKKNhIVe2iTTUVgxw/l/X47QFCgUTRvHyMi4c3ZA1mOPF+i7wwB93KihtlMKZYT9fU097KY80EIkr27CS/mEUhmvlBCx2ATaCWs1ev/igjDwIHKURQT2+gHVCecQMG+qnhzTWIgQN+/UfZJX42kqAMNTI53KrIJNJH9JjTzbt8rgXX+WkFW8UcWNxf2DVYxn67cfUpq9GX17uGTj87E7Qp546iF57/HyK+465Sn7hcf8LRWt+HQJA1+riJ1FCku+g4bTUYEd1shKTW1qH5P+pcB5BbngARuUP0wC0A=
